openapi: 3.0.0
info:
  description: >
    For the latest release information please check our [release notes](https://developer.test-app.com/release_notes).
    The Test App API exposes integrations endpoint and related functions.
  version: 'unstable'
  title: 'Test App'
  termsOfService: 'https://test-app.com/terms/'
  contact:
    email: 'heartyoh@hatiolab.com'
  license:
    name: MIT
    url: http://mit-license.org/
tags:
  - name: 'test-app'
    description: 'API for read, create and update test-apps'
schemes:
  - 'https'
  - 'http'
servers:
  - url: '/api/unstable'

components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    bearerAuth:
      type: http
      scheme: bearer

security:
  - basicAuth: []
  - bearerAuth: []
responses:
  UnauthorizedError:
    description: Unauthorized

externalDocs:
  description: 'Find out about our release notes'
  url: 'https://developer.test-app.com/release_notes'
